config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount BlacklightDynamicSitemap::Engine => '/'

  mount Arclight::Engine => '/'
  mount Sidekiq::Web => '/sidekiq'

  root 'landing_page#index'
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end
  devise_for :users

  concern :exportable, Blacklight::Routes::Exportable.new
  concern :hierarchy, Arclight::Routes::Hierarchy.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :hierarchy
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  get '/download/:id' => 'download#show'

  get '/search_tips' => 'catalog#search_tips'

  get '/using-this-site' => 'using_this_site#index'

  # Match ARKs that contain:
  # - a repository shoulder (one letter followed by one digit)
  # - a UUID (with or without hyphens)
  # In the ARK spec, strings that differ only by hyphens are considered identical
  # rubocop :disable Layout/LineLength
  get '/findingaid/*ark_id', to: 'finding_aids#resolve', as: :findingaid,
                             constraints: lambda { |req|
                               req.params[:ark_id] =~ %r{\Aark:/#{Settings.ark_naan}/[a-z]\d(?:[0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\z}i
                             }
  # rubocop :enable Layout/LineLength

  resource :feedback, only: :create

  # Cloudflare turnstile bot challenges via bot_challenge_page gem
  post '/challenge', to: 'bot_challenge_page/bot_challenge_page#verify_challenge', as: :bot_detect_challenge

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
# rubocop:enable Metrics/BlockLength

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

# Override of Blacklight's BookmarksController to remove the group toggle.
class BookmarksController < CatalogController
  include Blacklight::Bookmarks

  configure_blacklight do |config|
    config.index.respond_to.csv = true
    config.view_config(:index).collection_actions.delete(:group_toggle)
    config.default_per_page = 50
    # config.add_show_tools_partial(:email, callback: :email_action, validator: :validate_email_params)
  end
end

app/views/bookmarks/_clear_bookmarks_widget.html.erb
<%# Override from Blacklight to set button classes %>
<%= link_to t('blacklight.bookmarks.clear.action_title'), clear_bookmarks_path,
    data: {
      turbo_method: :delete,
      turbo_confirm: t('blacklight.bookmarks.clear.action_confirm')
    },
    class: 'clear-bookmarks btn btn-outline-secondary ms-1' %>

app/views/bookmarks/_email_form.html.erb
<%= form_tag url_for(controller: controller_name, action: "email"),
             data: { blacklight_modal: 'trigger' },
             id: 'email_form',
             class: "modal_form",
             method: :post do %>

  <div class="modal-body">
    <%= render '/shared/flash_msg' %>
    <div class="form-group row mb-3">
      <label class="control-label col-sm-2" for="to">
        <%= t('blacklight.email.form.to') %>
      </label>
      <div class="col-sm-10">
        <%= email_field_tag :to, params[:to], class: 'form-control', required: true %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <label class="control-label col-sm-2" for="message">
        <%= t('blacklight.email.form.message') %>
      </label>
      <div class="col-sm-10">
        <%= text_area_tag :message, params[:message], class: 'form-control' %>
        <%= render RecaptchaComponent.new(action: 'email')%>
      </div>
    </div>

    <% @response.documents&.each do |doc| %>
      <%=hidden_field_tag "id[]", doc.id %>
    <% end %>
    <%- if params[:sort] -%>
      <%= hidden_field_tag "sort", params[:sort] %>
    <%- end -%>
    <%- if params[:per_page] -%>
      <%= hidden_field_tag "per_page", params[:per_page] %>
    <%- end -%>
  </div>
  <div class="modal-footer">
    <button type="submit" data-turbo="false" class="btn btn-primary"> <%= t('blacklight.sms.form.submit') %></button>
  </div>
<% end %>

app/views/bookmarks/_email_modal.html.erb
<div class="modal fade" id="modal-bookmarks-email" tabindex="-1" aria-label="Email Bookmarks" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title h4"><%= t('bookmarks.email_link')%></h2>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= render 'email_form' %>
    </div>
  </div>
</div>

app/views/bookmarks/index.csv.erb
<%= CsvService.response_to_csv(response: @response).html_safe %>

app/views/bookmarks/index.html.erb
<% @page_title = t('blacklight.bookmarks.page_title', application_name: application_name) %>

<div id="content" class="col-md-12">
  <h1 class='page-heading pt-4'><%= t('blacklight.bookmarks.title') %></h1>

  <%= render BookmarkToolsComponent.new(response: @response, params:)%>

  <% if current_or_guest_user.blank? %>
    <h2 class='section-heading'><%= t('blacklight.bookmarks.need_login') %></h2>
  <% elsif @response.documents.blank? %>
    <h2 class='section-heading'><%= t('blacklight.bookmarks.no_bookmarks') %></h2>
  <% else %>
    <%= render 'sort_and_per_page' %>
    <h2 class='section-heading visually-hidden'><%= t('blacklight.bookmarks.list_title') %></h2>
    <%= render_document_index @response.documents %>
    <%= render 'results_pagination' %>
  <% end %>
</div>

<%= render 'email_modal' %>